# Generated by Django 5.0 on 2024-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brand_brandsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='menu',
            field=models.FileField(blank=True, upload_to='files/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='number',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
