# Generated by Django 5.0 on 2024-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_brand_menu_alter_brand_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
