# Generated by Django 5.0 on 2024-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('X', 'X'), ('Tiktok', 'Tiktok')], default='Facebook', max_length=12),
        ),
    ]
