# Generated by Django 5.0 on 2024-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_share_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/%y/%m/%d')),
                ('link', models.URLField()),
                ('kind', models.CharField(choices=[('Boycotted', 'Boycotted'), ('Alternative', 'Alternative')], default='Alternative', max_length=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['-created_at']},
        ),
    ]
