# Generated by Django 5.0 on 2024-10-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_brandsocial_social_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='media',
            field=models.FileField(null=True, upload_to='files/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='share',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
