# Generated by Django 5.0 on 2024-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_share_media_share_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='files/%y/%m/%d'),
        ),
    ]
