# Generated by Django 5.0 on 2024-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_share_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
                ('name', models.CharField(max_length=600)),
                ('kind', models.CharField(choices=[('Boycotted', 'Boycotted'), ('Alternative', 'Alternative')], default='Alternative', max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
